
NOMBRE	        LOCALIDAD	    ESTADIO	         PRESUPUESTO	CAMPEON
F.C.BARCELONA	BARCELONA	SPOTIFY CAMP NOU	 300.000.000      SI
R.MADRID	    MADRID	    SANTIAGO BERNABEU	 500.000.000	  SI
R.SOCIEDAD	    SAN SEBASTIAN	REALE ARENA	     60.000.000	      SI
ATHLETIC DE BILBAO	BILBAO	    SAN MAMÉS	     90.000.000	      SI
R.BETIS	        SEVILLA	    BENITO VILLAMARÍN	 60.000.000	      NO
ATLÉTICO DE MADRID	MADRID	WANDA STADIUM	     250.000.000	  SI
OSASUNA	        PAMPLONA	   EL SADAR	         30.000.000	      NO
VILLARREAL	VILLARREAL	ESTADIO DE LA CERÁMICA	 50.000.000	      NO
RAYO VALLECANO	MADRID	    VALLECAS	         15.000.000	      NO
MALLORCA	    MALLORCA	    SAN MOIX	     20.000.000	      NO
VALLADOLID	    VALLADOLID	    ZORRILLA	     15.000.000	      NO
VALENCIA	    VALENCIA	    MESTALLA	     100.000.000	  SI
GIRONA	        GIRONA	        MONTILIVI	     15.000.000	      NO
ALMERÍA	        ALMERÍA	    JUEGOS DEL MEDITERRÁNEO	25.000.000	  NO
GETAFE	        GETAFE	        ALFONSO PÉREZ	 25.000.000	      NO
ESPANYOL	    BARCELONA	    RCDE STADIUM	 30.000.000	      NO
SEVILLA	        SEVILLA	        SÁNCHEZ PIZJUÁN	 99.000.000	      SI
CELTA	        VIGO	        BALAÍDOS	     40.000.000	      NO
CÁDIZ	        CÁDIZ	    NUEVO MIRANDILLA	 15.000.000	      NO
ELCHE	        ELCHE	    MARTÍNEZ VALERO	      9.000.000	      NO



1.	CREA UNA BASE DE DATOS “LIGAFC”.

CREATE DATABASE ligafcasir;

2.	CREA UNA TABLA QUE TENGA LOS CAMPOS QUE CONFORMAN LA CABECERA DE LA TABLA.

USE ligafcasir;

CREATE TABLE equipos (
    nombre VARCHAR(25) NOT NULL,
    localidad VARCHAR(25) NOT NULL,
    estadio VARCHAR(55) NOT NULL,
    presupuesto INT(10) NOT NULL,
    campeon TINYINT(1) NOT NULL -- "valdría" poner boolean
);


3.	INSERTA LA INFORMACIÓN QUE SE FACILITA EN LA TABLA.

INSERT INTO equipos (nombre, localidad, estadio, presupuesto, campeon) VALUES 
("F.C.BARCELONA", "BARCELONA", "SPOTIFY CAMP NOU", 300000000 ,1),
("R.MADRID", "MADRID", "SANTIAGO BERNABEU",	 500000000, 1),
("R.SOCIEDAD", "SAN SEBASTIAN", "REALE ARENA", 60000000, 1),
("ATHLETIC DE BILBAO", "BILBAO", "SAN MAMÉS",90000000 , 1),
("REAL BETIS", "SEVILLA", "BENITO VILLAMARÍN",60000000 ,0 ),
("ATLÉTICO DE MADRID", "MADRID", "WANDA STADIUM",250000000 , 1),
("OSASUNA", "PAMPLONA", "EL SADAR", 30000000, 0),
("VILLARREAL", "VILLARREAL", "ESTADIO DE LA CERÁMICA",50000000 , 0),
("RAYO VALLECANO", "MADRID", "VALLECAS",15000000 , 0),
("MALLORCA", "MALLORCA", "SAN MOIX", 20000000 , 0),
("VALLADOLID", "VALLADOLID", "ZORRILLA", 15000000, 0),
("VALENCIA", "VALENCIA", "MESTALLA", 100000000, 1),
("GIRONA", "GIRONA", "MONTILIVI",15000000 , 0),
("ALEMRÍA", "ALMERÍA", "JUEGOS DEL MEDITERRÁNEO", 25000000, 0),
("GETAFE", "GETAFE", "ALFONSO PÉREZ",25000000 , 0),
("ESPANYOL", "BARCELONA", "RCDE STADIUM", 30000000 , 0),
("SEVILLA", "SEVILLA", "SÁNCHEZ PIZJUÁN",99000000 , 1),
("CELTA", "VIGO", "BALAÍDOS",40000000 , 0),
("CÁDIZ", "CÁDIZ", "NUEVO MIRANDILLA",15000000 , 0),
("ELCHE", "ELCHE", "MARTÍNEZ VALERO",9000000 , 0);

4.	AGREGA UNA ID INT(10) AUTO INCREMENTAL.

ALTER TABLE equipos
ADD COLUMN id INT(10) AUTO_INCREMENT;

ERROR 1075 (42000): Incorrect table definition; there can be only one auto column and it must be defined as a key
COMO LA COLUMNA ID NO ESTÁ DEFINIDA COMO CLAVE, NO PODEMOS HACER AUTO INCREMENTAL.

5.	HAZ QUE LA ID SE SITÚE A LA IZQUIERDA DE LA TABLA.

ALTER TABLE equipos
MODIFY COLUMN id INT(10) AUTO_INCREMENT FIRST;

6.	HAZ QUE LA ID SEA CLAVE PRIMARIA.

ALTER TABLE equipos
MODIFY COLUMN id INT(10) PRIMARY KEY AUTO_INCREMENT;

7.	CAMBIA EL NOMBRE DE LA COLUMNA “LOCALIDAD” Y HACER QUE SE LLAME “CIUDAD”. 
MODIFY -> MODIFICAR TIPO DE DATOS Y/O LONGITUD DE COLUMNA
CHANGE -> RENOMBRAR COLUMNA Y MODIFICAR TIPO DE DATOS Y/O LONGITUD 
RENAME -> RENOMBRAR COLUMNA

ALTER TABLE equipos
RENAME COLUMN localidad TO ciudad;

8.	CREA UNA TABLA “ESTADIOS”:

ID	NOMBRE	            CAPACIDAD
1	SPOTIFY CAMP NOU	110.000
2	SANTIAGO BERNABEU	99.000
3	REALE ARENA	        55.000
4	SAN MAMÉS	        55.000
5	BENITO VILLAMARÍN	40.000
6	WANDA STADIUM	    75.000
7	EL SADAR	        30.000
8	ESTADIO DE LA CERÁMICA	25.000
9	VALLECAS	        20.000
10	SAN MOIX	        15.000
11	ZORRILLA	        18.000
12	MESTALLA	        55.000
13	MONTILIVI	        17.000
14	JUEGOS DEL MEDITERRÁNEO	18.000
15	ALFONSO PÉREZ	    21.000
16	RCDE STADIUM	    25.000
17	SÁNCHEZ PIZJUÁN	    60.000
18	BALAÍDOS	        19.000
19	NUEVO MIRANDILLA	12.000
20	MARTÍNEZ VALERO	    11.000

CREATE TABLE estadios(
    id INT(3) PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(55) NOT NULL,
    capacidad INT(6) NOT NULL
);

CREATE TABLE estadios(
    id INT(3) AUTO_INCREMENT,
    nombre VARCHAR(55) NOT NULL,
    capacidad INT(6) NOT NULL,
    PRIMARY KEY(id) 
);

INSERT INTO estadios (nombre, capacidad) VALUES
("SPOTIFY CAMP NOU",110000),
("SANTIAGO BERNABEU",99000),
("REALE ARENA", 55000),
("SAN MAMÉS",55000),
("BENITO VILLAMARÍN",40000),
("WANDA STADIUM",75000),
("EL SADAR",30000),
("ESTADIO DE LA CERÁMICA",25000),
("VALLECAS",20000),
("SAN MOIX",15000),
("ZORRILLA",18000),
("MESTALLA",55000),
("MONTILIVI",17000),
("JUEGOS DEL MEDITERRÁNEO",18000),
("ALFONSO PÉREZ",21000),
("RCDE STADIUM", 25000),
("SÁNCHEZ PIZJUÁN",60000),
("BALAÍDOS",19000),
("NUEVO MIRANDILLA",12000),
("MARTÍNEZ VALERO",11000);


9.	HAZ QUE LA COLUMNA “CAMPEON” DE LA TABLA “EQUIPOS” SE SITÚE A LA DERECHA DEL NOMBRE DEL EQUIPO.
ALTER TABLE equipos
MODIFY COLUMN campeon TINYINT(1) NOT NULL AFTER nombre;

10.	ELIMINA LA TABLA “EQUIPOS”.

DROP TABLE equipos;

11.	VUELVE A CREAR LA TABLA “EQUIPOS” Y VUELVE A DEJARLA COMO ESTABA ANTES DEL ENUNCIADO 10.


12.	CREA UNA TABLA QUE SE LLAME “LIGAS” QUE TENGA LA SIGUIENTE APARIENCIA:

ID	NOMBRE	     PAIS
1	LIGA BBVA	ESPAÑA
2	PREMIER	    INGLATERRA
3	CALCIO	    ITALIA
4	MLS	        EEUU
5	LIGUE 1	    FRANCIA

CREATE TABLE ligas (
    id INT(2) PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(15) NOT NULL,
    pais VARCHAR(25) NOT NULL
);

CREATE TABLE ligas (
    id INT(2) AUTO_INCREMENT,
    nombre VARCHAR(15) NOT NULL,
    pais VARCHAR(25) NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO ligas (nombre, pais) VALUES
("LIGA BBVA", "ESPAÑA"),
("PREMIER", "INGLATERRA"),
("CALCIO", "ITALIA"),
("MLS", "EEUU"),
("LIGUE 1", "FRANCIA");


13.	HAZ QUE LA COLUMNA PRESUPUESTO ACEPTE NÚMEROS DECIMALES CON 2 DECIMALES.
ALTER TABLE equipos
MODIFY COLUMN presupuesto DECIMAL(12,2);
